# Generated by Django 5.1.1 on 2025-02-22 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_alter_prescriptions_patient'),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.patientmodel'),
        ),
    ]
